[build]
  publish = "/"
  
  [[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "/"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

	[plugins.inputs]

	# The base url of your site (optional, default = main URL set in Netlify)
	baseUrl = "https://scribblesinfo.com"

	# Path to the sitemap URL (optional, default = /sitemap.xml)
	sitemapPath = "/sitemap.xml"

	# Enabled providers to submit sitemap to (optional, default = 'google', 'bing'). Possible providers are currently only 'google' and 'bing'.
	providers = [
		"google",
		"bing"
	]
	
	[[plugins]]
  package = "netlify-plugin-fetch-feeds"

  [plugins.inputs]
    # Where should data files reside
    dataDir = "site/"

    # All the feeds we wish to gather for use in the build

    [[plugins.inputs.feeds]]
      name = "Scribblesinfo"
      url = "https://scribblesinfo/feed.json"
      ttl = 3600
    [[plugins.inputs.feeds]]
      name = "Scribbesinfo"
      url = "https://www.scribblesinfo.com/facts/index.xml"
      ttl = 86400
